### ISSUE TITLE
Extremely long load time / Failure to load

### ISSUE THREAD

**Issue by KawaiiLinusu** [gd-edit/GDE#146] opened 2019-11-17 18:13 UTC
I just got GD-Edit. I open the program, avast checks it and lets it start, but nothing is happening. I can't figure out why. Third restart, it doesnt check, and it still doesnt start.

**Comment by Altenhh** [comment] 2019-11-17 18:16
could you provide us some logs? they are located in `%appdata%/Roaming/GD Edit/logs`

**Comment by KawaiiLinusu** [comment] 2019-11-17 18:19
[performance.log](https://github.com/gd-edit/GDE/files/3855933/performance.log)
[runtime.log](https://github.com/gd-edit/GDE/files/3855934/runtime.log)
Bing

**Comment by KawaiiLinusu** [comment] 2019-11-17 18:20
(Quick note of info: I'm on the latest pre-release)

**Comment by Altenhh** [comment] 2019-11-17 18:22
could i please get your discord tag so that i can contact you?

**Comment by KawaiiLinusu** [comment] 2019-11-17 18:22
TurkeyQueen#7530 (Will be updated to something else on December 1st 2019)

**Comment by Altenhh** [comment] 2019-11-17 21:48
Going to close this as its essentially a duplicate of #102

**Closed by Altenhh** 2019-11-17 21:48 UTC
Labels: Performance
